Explicit zeropad functions $\Rightarrow$ preparing for C logic

In [2]:
import numpy as np

In [87]:
def zeropad1_0(array, edges, xp):

    largest_block = xp.diff(edges).max()
    n_blocks = edges.size - 1

    if array.ndim == 1:   #should only be the case for the noise matrix
        out = xp.zeros((n_blocks, int(largest_block)))
    else:
        out  = xp.zeros((n_blocks, int(largest_block), int(array.shape[1])))

    for block, (start, stop) in enumerate(zip(edges, edges[1:])):
        start, stop = int(start), int(stop)
        out[block, :stop - start] = array[start:stop]
    
    return out

In [88]:
def zeropad1_1(array, edges, xp):
    #assuming only works for a 1d array for now

    largest_block = xp.diff(edges).max()
    n_blocks = edges.size - 1

    if array.ndim == 1:   #should only be the case for the noise matrix
        out = xp.zeros((n_blocks, int(largest_block)))
    else:
        out  = xp.zeros((n_blocks, int(largest_block), int(array.shape[1])))

    for block in range(n_blocks):
        start = edges[block]
        stop = edges[block + 1]
        block_size = stop - start

        for i in range(block_size):
            out[block][i] = array[start + i]

    return out

In [89]:
xp = np
n_bls = 10
edges = xp.unique(xp.random.randint(1, n_bls-1, size = 3))
edges = xp.concatenate((np.array([0]), edges, np.array([n_bls])))

array = np.random.rand(n_bls)
# array = np.arange(n_bls)

print(array)
print(edges)

zeropadded_array = zeropad1_1(array, edges, xp = np)

print(zeropadded_array)
print()
print(np.diff(edges).max())
print()
print(len(edges - 2))
print()
print(edges.shape[0] - 1)
print()
print(int(np.diff(edges).max()) * int(edges.shape[0] - 1))
print(np.diff(edges).max())
print(zeropadded_array.reshape(1, int(np.diff(edges).max()) * int(edges.shape[0] - 1)))


[0.43396076 0.36697908 0.52108625 0.4219875  0.73230306 0.12678785
 0.18842986 0.11617267 0.99220404 0.54639744]
[ 0  5  7  8 10]
[[0.43396076 0.36697908 0.52108625 0.4219875  0.73230306]
 [0.12678785 0.18842986 0.         0.         0.        ]
 [0.11617267 0.         0.         0.         0.        ]
 [0.99220404 0.54639744 0.         0.         0.        ]]

5

5

4

20
5
[[0.43396076 0.36697908 0.52108625 0.4219875  0.73230306 0.12678785
  0.18842986 0.         0.         0.         0.11617267 0.
  0.         0.         0.         0.99220404 0.54639744 0.
  0.         0.        ]]


In [14]:
print(np.array([0]))

[0]


In [9]:
x = np.random.randint(1, 10, 10)

print(x)

[2 1 7 7 3 2 9 3 5 1]


In [4]:
array = np.array([1,2,3,4,5,6,7,8])

print(array[:4-2])

[1 2]
