In [2]:
import numpy as np

In [5]:
arr = np.random.rand(10)
print(arr.shape)
print(arr.shape[0])

(10,)
10


In [12]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 0.8, 9, 10], dtype = np.int32)
print(ar)

[ 1  2  3  4  5  6  7  0  9 10]


In [7]:
ar = np.random.rand(10, 2)
arFlat = ar.flatten("F")
print(ar)
print(ar.shape)
print(arFlat)
print(arFlat.shape)

[[0.65704436 0.51287056]
 [0.74021226 0.60150044]
 [0.32607802 0.64482033]
 [0.47608413 0.16770635]
 [0.12936525 0.99849377]
 [0.65886588 0.73263362]
 [0.62513028 0.66768149]
 [0.62658016 0.60220632]
 [0.31857893 0.14230961]
 [0.82617523 0.61730285]]
(10, 2)
[0.65704436 0.74021226 0.32607802 0.47608413 0.12936525 0.65886588
 0.62513028 0.62658016 0.31857893 0.82617523 0.51287056 0.60150044
 0.64482033 0.16770635 0.99849377 0.73263362 0.66768149 0.60220632
 0.14230961 0.61730285]
(20,)


In [124]:
arr3d = np.linspace(1, 32, 32, dtype="int32")
arr3d = arr3d.reshape(4, 4, 2)
arr2d = arr3d.reshape(16, 2)
flatArr = arr3d.flatten()
print(arr3d)
print(arr2d)
print(flatArr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]
 [31 32]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32]


In [126]:
n_blocks = arr3d.shape[0]   #this is similar to the 'depth' entry
n_cols = arr3d.shape[2]
n_rows = arr3d.shape[1]


print(flatArr)
print(arr3d)
for block in range(n_blocks):
    for row in range(n_rows):
        for col in range(n_cols):
            print(flatArr[n_cols*(block*n_rows + row) + col])



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32


In [107]:
import time
stride = 3000
test_arr = np.random.rand(stride,stride)
test_arr = test_arr.flatten()

init_arr = np.zeros((test_arr.shape))
print(init_arr.shape)

starttime = time.time()
for rowid in range(stride):
    for colid in range(stride):
        init_arr[rowid*stride + colid] = test_arr[rowid*stride + colid]

stoptime = time.time()
print(stoptime - starttime)

(9000000,)
2.8698441982269287


In [109]:
import time
stride = 3000
test_arr = np.random.rand(stride,stride)
test_arr = test_arr.flatten()

init_arr = np.zeros((test_arr.shape))
print(init_arr.shape)

starttime = time.time()
for colid in range(stride):
    for rowid in range(stride):
        init_arr[rowid*stride + colid] = test_arr[rowid*stride + colid]

stoptime = time.time()
print(stoptime - starttime)

(9000000,)
3.08970308303833
