In [1]:
import numpy as np

In [24]:
np.random.seed(10)
A = np.asfortranarray(np.random.rand(3, 4)).astype("float64")
print(A.strides)
print(A)

(8, 24)
[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]]


In [31]:
np.random.seed(10)
A = np.random.rand(3, 2).astype("float32")
print(A.strides)
print(A)

(8, 4)
[[0.77132064 0.02075195]
 [0.6336482  0.74880385]
 [0.49850702 0.22479665]]


In [16]:
import numpy as np
A = np.random.rand(2,3,4)
B = np.random.rand(2,4,2)

In [17]:
print(A)
print(B)

[[[0.74987035 0.45185701 0.05218816 0.6429198 ]
  [0.45532188 0.96088693 0.5163997  0.65929938]
  [0.56363125 0.57605814 0.56455542 0.56142315]]

 [[0.16748556 0.33569563 0.79545499 0.38230476]
  [0.42904561 0.18618033 0.88046954 0.86373619]
  [0.04520367 0.92358359 0.46244384 0.78509776]]]
[[[0.68564054 0.52347652]
  [0.38361285 0.80877927]
  [0.10585436 0.58969699]
  [0.84861015 0.97607683]]

 [[0.46451058 0.75538955]
  [0.74014437 0.40096344]
  [0.73059108 0.94272902]
  [0.53998881 0.20409722]]]


In [18]:
C = A@B
print(C)

[[[1.23859227 1.41630643]
  [1.29494701 1.96354194]
  [1.14362177 1.64186037]]

 [[1.11385466 1.08904435]
  [1.44676762 1.40507841]
  [1.46638413 1.00066513]]]
