In [1]:
import numpy as np

In [24]:
np.random.seed(10)
A = np.asfortranarray(np.random.rand(3, 4)).astype("float64")
print(A.strides)
print(A)

(8, 24)
[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]]


In [31]:
np.random.seed(10)
A = np.random.rand(3, 2).astype("float32")
print(A.strides)
print(A)

(8, 4)
[[0.77132064 0.02075195]
 [0.6336482  0.74880385]
 [0.49850702 0.22479665]]
